apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${branch}-server-ident
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ${branch}-server
  name: ${branch}-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${branch}-server
  strategy: {}
  template:
    metadata:
      labels:
        app: ${branch}-server
    spec:
      containers:
      - image: nginx
        name: nginx
        env:
        - name: BRANCH
          value: ${branch}
        - name: COMMIT
          value: ${commit}
