apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${branch}-server-ident
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  strategy: {}
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ["/bin/sh", "-c", "tail -f /dev/null"]
        env:
        - name: BRANCH
          value: ${branch}
        - name: COMMIT
          value: ${commit}
