apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${branch}-server-ident
  labels:
    environment: ${branch}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
    environment: ${branch}
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy: {}
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ["/bin/sh", "-c", "tail -f /dev/null"]
        env:
          - name: ENV
            value: ${branch}
