apiVersion: v1
kind: ServiceAccount
metadata:
  name: server-ident
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  strategy: {}
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ["/bin/sh", "-c", "tail -f /dev/null"]
